version: '3.4'

networks:
  shared_network:
    external: true

services:
  db:
    image: postgres:11.4
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: coinage
      POSTGRES_DB: coppermint
    ports:
      - 5432:5432
    networks:
      - shared_network
  coppermint:
    build:
      context: .
      target: dev
    command: ["python", "manage.py", "runserver", "0.0.0.0:8010"]
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DATABASE_URL=postgresql://root:coinage@db:5432/coppermint
      - DJANGO_SETTINGS_MODULE=coppermint.settings
      - CACHE_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - 8010:8010
    links:
      - db:db
    depends_on:
      - db
      - redis
    networks:
      - shared_network
  redis:
    image: redis:3.2.11-alpine
    ports:
      - "6379:6379"
  celery:
    container_name: celery
    build:
      context: .
      target: dev
    command: ["celery", "-B", "-A", "coppermint", "--concurrency=5", "worker"]
    environment:
      - DJANGO_SETTINGS_MODULE=coppermint.settings
      - CACHE_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://root:coinage@db:5432/coppermint
