# Generated by Django 2.2.2 on 2019-07-28 11:45

import coppermint.coinbase_pro.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.CharField(max_length=191, primary_key=True, serialize=False)),
                ("client_order_id", models.UUIDField()),
                ("price", models.FloatField(blank=True, null=True)),
                ("size", models.FloatField(blank=True, null=True)),
                ("funds", models.FloatField()),
                ("product_id", models.CharField(default="BTC-EUR", max_length=191)),
                ("side", models.CharField(choices=[("buy", "Buy order"), ("sell", "Sell order")], max_length=191)),
                ("stp", models.CharField(blank=True, default="dc", max_length=191, null=True)),
                ("order_type", models.CharField(default="limit", max_length=191)),
                ("stop", models.CharField(blank=True, max_length=191, null=True)),
                ("stop_price", models.FloatField(blank=True, null=True)),
                (
                    "time_in_force",
                    models.CharField(
                        blank=True,
                        default=coppermint.coinbase_pro.constants.OrderLifeTime("GTC"),
                        max_length=191,
                        null=True,
                    ),
                ),
                (
                    "cancel_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minute", "Cancel after 1 minute"),
                            ("hour", "Cancel after 1 hour"),
                            ("DAY", "Cancel after 24 hours"),
                        ],
                        max_length=191,
                        null=True,
                    ),
                ),
                ("post_only", models.NullBooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fill_fees", models.FloatField()),
                ("filled_size", models.FloatField()),
                ("executed_value", models.FloatField()),
                ("status", models.CharField(max_length=191)),
                ("settled", models.BooleanField(default=False)),
            ],
        )
    ]
