# Generated by Django 2.2.3 on 2019-07-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("coinbase_pro", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SimplePriceOscillationStrategy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("buy_percentage_difference", models.FloatField(default=0.0)),
                ("sell_percentage_difference", models.FloatField(default=0.0)),
                ("starting_funds", models.FloatField(default=0.0)),
                ("current_funds", models.FloatField(default=0.0)),
                ("max_order_funds", models.FloatField(default=0.0)),
                ("max_total_funds", models.FloatField(default=0.0)),
                ("accrued_fees", models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(model_name="order", name="funds", field=models.FloatField(blank=True, null=True)),
        migrations.CreateModel(
            name="OrderChain",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coinbase_pro.SimplePriceOscillationStrategy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedOrder",
            fields=[
                (
                    "order_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="coinbase_pro.Order",
                    ),
                ),
                ("index", models.BigIntegerField()),
                (
                    "order_chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coinbase_pro.OrderChain",
                    ),
                ),
            ],
            options={"unique_together": {("order_chain", "index")}},
            bases=("coinbase_pro.order",),
        ),
    ]
