# Generated by Django 2.2.3 on 2019-08-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("coinbase_pro", "0002_auto_20190728_2100")]

    operations = [
        migrations.AddField(
            model_name="order", name="stop_type", field=models.CharField(blank=True, max_length=191, null=True)
        ),
        migrations.AddField(
            model_name="simplepriceoscillationstrategy",
            name="product_id",
            field=models.CharField(default="BTC-EUR", max_length=191),
        ),
    ]
