# Generated by Django 2.2.3 on 2019-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("coinbase_pro", "0003_auto_20190804_1808")]

    operations = [
        migrations.AddField(
            model_name="simplepriceoscillationstrategy", name="starting_price", field=models.FloatField(null=True)
        )
    ]
